### PR TITLE
Created outline skeleton for navigation

### PR DESCRIPTION
**Pull request by WSINTRA**
Its a stack nav, inside of a tab nav, inside of a drawer nav !!!!

### CODE REVIEW

**Comment by speckworks** [comment]
Wow.. cool.  We doing the Shitake similar to Tavour for Nav I take it?

**Comment by WSINTRA** [comment]
> Wow.. cool. We doing the Shitake similar to Tavour for Nav I take it?

We don't have too, but it seems like a good navigation system, The drawer is always on top, and then you have your tab windows that each render anything we want, in this case I only put a product page and made it a stack but I'm pretty sure we could also have a bottom tab that links into a top tab navigator,

**Comment by speckworks** [comment]
OK. Cool.  @WSINTRA Can we add some 3-D imaging to the APP.  Do you use D3?  I wonder what works best with RN

**Comment by speckworks** [comment]
hmm. a bit dated, but found this:  https://medium.com/the-react-native-log/animated-charts-in-react-native-using-d3-and-art-21cd9ccf6c58

**Comment by speckworks** [comment]
And this pinch gesture. Damn!  Talk about maths?  https://www.youtube.com/watch?v=oDTsu7tK0H4

**Comment by speckworks** [comment]
Damn. How do I scan qr code in android again? Is there an app i need to install?

**Pull request merged**
